### ISSUE TITLE
Problem with running the demo

### ISSUE THREAD

**Issue by mxseba** [amaurym/login-with-metamask-demo#219]
Hello!
Demo using yarn
The browser displays the following errors:

src\App\App.tsx
  Line 36:8:  Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method

src\Profile\Profile.tsx
  Line 38:9:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 39:9:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 60:9:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 61:9:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 61:9:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 72:55:  Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 88:8:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 90:8:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 94:8:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 94:8:   Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
  Line 96:27:  Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method

How do I fix this?

**Comment by sledmonkey** [comment]
Same here, doesn't appear to work anymore.
